matrix:
  include:

    # linux gcc
    - os: linux
      dist: bionic
      sudo: required
      compiler: gcc
      env:
       - QT_BASE=511
      addons:
       apt:
         update: true
         packages:
            - cmake
            - qt5-default
            - libqt5multimedia5
            - libqt5opengl5-dev

env:
  global:

language: cpp

sudo: false

before_install:
  # only build the first port if running a coverity scan. otherwise coverity will attempt to analyze all the builds
  - cd yabause
  - mkdir build
  - cd build

script:
  - cmake ..
  - make

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Francois CARON"
  - git config --local user.email "francois.caron.perso@gmail.com"
  - cd ..
  - mkdir releases
  - cp build/src/port/qt/kronos releases/kronos
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: 
    secure: 163c3762b26786dd145de85248d93d5d36c786c7
  file: releases/kronos
  skip_cleanup: true
  on:
    tags: true

