matrix:
  include:

    # linux gcc
    - os: linux
      dist: bionic
      sudo: required
      compiler: gcc
      env:
       - QT_BASE=511
      addons:
       apt:
         update: true
         packages:
            - cmake
            - libqt5multimedia

env:
  global:

language: cpp

sudo: false

before_install:
  # only build the first port if running a coverity scan. otherwise coverity will attempt to analyze all the builds
  - cd yabause
  - mkdir build
  - cd build

script:
  - cmake  ..
  - make
